make_directory:
    image: nginx:alpine
    script:
        - echo "Hello User"
        - mkdir bin
        - cd bin
        - touch data
        - echo "First line of statement" >> data
        - cat data
