name: Simple Pipeline
on: [push]
jobs:
  dir:
    runs-on: ubuntu-latest
    steps:
      - run: | 
            echo "Make file"
            mkdir -p folder
            cd folder
            touch data
            echo "Success" > data
            echo "Time for execution: $(date)" >> data
            cat data
